<?php

namespace App\Models;

use App\Enums\NotificationType;
use App\Traits\Syncable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use OpenApi\Attributes as OA;
use Whilesmart\Agents\Contracts\HasAgentResource;
use Whilesmart\Agents\Resources\AgentResource;
use Whilesmart\Agents\Resources\ResourceField;

#[OA\Schema(
    schema: 'Notification',
    properties: [
        new OA\Property(property: 'id', type: 'integer'),
        new OA\Property(property: 'type', type: 'string', enum: ['reminder', 'alert', 'achievement', 'system']),
        new OA\Property(property: 'title', type: 'string'),
        new OA\Property(property: 'body', type: 'string', nullable: true),
        new OA\Property(property: 'data', type: 'object', nullable: true),
        new OA\Property(property: 'read_at', type: 'string', format: 'date-time', nullable: true),
        new OA\Property(property: 'created_at', type: 'string', format: 'date-time'),
    ],
    type: 'object'
)]
class Notification extends Model implements HasAgentResource
{
    use HasFactory;
    use Syncable;

    protected $fillable = [
        'user_id',
        'type',
        'title',
        'body',
        'data',
        'read_at',
    ];

    protected $casts = [
        'data' => 'array',
        'read_at' => 'datetime',
        'type' => NotificationType::class,
    ];

    protected $appends = ['last_synced_at', 'client_generated_id'];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function isRead(): bool
    {
        return $this->read_at !== null;
    }

    public function markAsRead(): void
    {
        if (! $this->isRead()) {
            $this->read_at = now();
            $this->save();
        }
    }

    public function markAsUnread(): void
    {
        $this->read_at = null;
        $this->save();
    }

    public function scopeUnread($query)
    {
        return $query->whereNull('read_at');
    }

    public function scopeRead($query)
    {
        return $query->whereNotNull('read_at');
    }

    public function scopeOfType($query, NotificationType $type)
    {
        return $query->where('type', $type);
    }

    public static function agentResource(): AgentResource
    {
        return new AgentResource(
            name: 'notifications',
            model: self::class,
            table: 'notifications',
            description: 'Messages Trakli has sent the user, such as a budget warning. Generated by the system.',
            aliases: ['alerts', 'messages'],
            labelColumn: 'title',
            ownerKey: 'user_id',
            readable: [
                ResourceField::key(),
                ResourceField::string('type', 'What kind of notification it is'),
                ResourceField::string('title', 'Notification headline'),
                ResourceField::text('body', 'Notification text'),
                ResourceField::datetime('read_at', 'When the user read it, empty if unread'),
                ResourceField::internal('user_id'),
                ResourceField::datetime('created_at', 'When it was sent'),
            ],
        );
    }
}
