name: Tests

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  coverage:
    name: Update Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Check Coverage
        uses: whilesmart/workflows/php/coverage/update@main
